### ISSUE TITLE
In openshift orign 3.9, Container is waiting maven-r6dn5

### ISSUE THREAD

**Issue by haijunjiang** [siamaksade/openshift-cd-demo#103]
Where can I modify the maven image address, the default address is " pulling image "registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7""

thanks

**Comment by siamaksade** [comment]
Refer to the Jenkins on OpenShift docs:
https://docs.openshift.com/container-platform/3.10/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in
