### ISSUE TITLE
pulling docker image jenkins-agent-maven-35-rhel7 failed on centos cause by missing /etc/rhsm/ca/redhat-uep.pem file

### ISSUE THREAD

**Issue by isnuryusuf** [siamaksade/openshift-cd-demo#110]
since on centos latest doesnt have correct ca certificate, so we need to create it

wget http://mirror.centos.org/centos/7/os/x86_64/Packages/python-rhsm-certificates-1.19.10-1.el7_4.x86_64.rpm

rpm2cpio python-rhsm-certificates-1.19.10-1.el7_4.x86_64.rpm | cpio -iv --to-stdout ./etc/rhsm/ca/redhat-uep.pem | tee /etc/rhsm/ca/redhat-uep.pem

docker pull registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7

**Comment by siamaksade** [comment]
Fixed with 9153f630d09427fd36bbe02bbe0746fcad03f786
