### ISSUE TITLE
Red Hat Maven repository is not working due to HTTP 500 error code

### ISSUE THREAD

**Issue by isnuryusuf** [siamaksade/openshift-cd-demo#111]
Following Maven Repo is not working

https://maven.repository.redhat.com/ga/
https://maven.repository.redhat.com/techpreview/all

Solution:
https://access.redhat.com/solutions/3320981

download :
jboss-eap-7.0.0-maven-repository.zip
jboss-eap-7.0.1-incremental-maven-repository.zip
from Red Hat customer portal

Extract on same folder, and publish as HTTP Server
on Nexus, create maven Repository Proxy, point to your URL
on Maven-public-all repository, add member repository and put in the top

**Comment by siamaksade** [comment]
This has been a temporary hick-up. The work now
