### ISSUE TITLE
no matches for kind "RoleBinding" in version "v1"

### ISSUE THREAD

**Issue by medined** [siamaksade/openshift-cd-demo#113]
I started a new OKD cluster. Then ran the manual setup:
```
oc new-project dev --display-name="Tasks - Dev"
oc new-project stage --display-name="Tasks - Stage"
oc new-project cicd --display-name="CI/CD"
oc policy add-role-to-group edit system:serviceaccounts:cicd -n dev
oc policy add-role-to-group edit system:serviceaccounts:cicd -n stage
oc new-app -n cicd -f cicd-template.yaml
```
On the last command, which has worked flawlessly many times before, I ran into the following failure:

```
   error: no matches for kind "RoleBinding" in version "v1"
    error: no matches for kind "BuildConfig" in version "v1"
```

I also see:

```
Failure summary:
  1. Hosts:    54.145.176.108
     Play:     OpenShift Metrics
     Task:     Check that python-passlib is available on the control host
     Message:  python-passlib rpm must be installed on control host
****
```
I do have the python-passlib installed on my host ubuntu laptop. I'm betting this error is caused by the following line in my inventory file:

```
openshift_metrics_install_metrics=true
```

I'll remove it to see what hapens.

**Comment by medined** [comment]
Just to quickly follow up. I did remove the 'install metrics' line from inventory then I rebuilt the cluster from scratch. No luck. I am mystified since I've done this many times without a problem.

**Comment by siamaksade** [comment]
What's the output of `oc version`?

**Comment by medined** [comment]
I just recreated my OKD v3.11 cluster. I am using oc v3.11.0. And the openshift-cd-demo project is working just fine. Thanks again for making this available.

**Comment by gsaslis** [comment]
FWIW - I had a similar error with an oc 3.11 client (cli) accessing an oc 3.9 server

downgrading openshift-cli to 3.9 fixed this for me ( `brew switch openshift-cli 3.9.0` )
