### ISSUE TITLE
che-single-user.yml is missing again so no che install

### ISSUE THREAD

**Issue by kjw3** [siamaksade/openshift-cd-demo#118]
https://raw.githubusercontent.com/minishift/minishift/master/addons/che/templates/che-single-user.yml  has been removed from minishift addon templates. Not sure where it is located now.

oc process -f https://raw.githubusercontent.com/minishift/minishift/master/addons/che/templates/che-single-user.yml

**Comment by siamaksade** [comment]
Fixed with e398e385c5523a7a4bb431ddd0aee791f8f225b8
