### ISSUE TITLE
Deploy to DEV fails due to missing imagestream

### ISSUE THREAD

**Issue by ytra** [siamaksade/openshift-cd-demo#22]
[Pipeline] stage (Deploy DEV)
Entering stage Deploy DEV
Proceeding
[Pipeline] sh
[tasks-cd-pipeline] Running shell script
- rm -rf oc-build
- mkdir -p oc-build/deployments
  [Pipeline] sh

[tasks-cd-pipeline] Running shell script
- cp target/openshift-tasks.war oc-build/deployments/ROOT.war
  [Pipeline] sh
  [tasks-cd-pipeline] Running shell script
  ++ cat /var/run/secrets/kubernetes.io/serviceaccount/token
- /usr/bin/oc --token=< snip snip >
  -server=https://openshift.default.svc.cluster.local --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt delete bc,dc,svc,route -l app=tasks -n dev

No resources found
[Pipeline] sh

[tasks-cd-pipeline] Running shell script
++ cat /var/run/secrets/kubernetes.io/serviceaccount/token
- /usr/bin/oc --token=< snip snip >
  -server=https://openshift.default.svc.cluster.local --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt new-build --name=tasks --image-stream=jboss-eap64-openshift --binary=true --labels=app=tasks -n dev

error: no match for "jboss-eap64-openshift"

The 'oc new-build' command will match arguments to the following types:
1. Images tagged into image streams in the current project or the 'openshift' project
   - if you don't specify a tag, we'll add ':latest'
2. Images in the Docker Hub, on remote registries, or on the local Docker engine
3. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to force the use of an image that was not matched

See 'oc new-build -h' for examples.
- true

**Comment by Jimhub214** [comment]
the same issue, what is the solution?

**Comment by Jimhub214** [comment]
I have fixed the problem instead to use the --image-stream=jboss-eap64-openshift I have used --image-stream=wildfly:latest
