### ISSUE TITLE
"master" ref not recognized during build for jenkins master and jenkins slave

### ISSUE THREAD

**Issue by VeerMuchandi** [siamaksade/openshift-cd-demo#25]
I0906 03:59:41.853507       1 source.go:197] Downloading "https://github.com/OpenShiftDemos/openshift-cd-demo.git" ...
I0906 03:59:48.514236       1 source.go:208] Cloning source from https://github.com/OpenShiftDemos/openshift-cd-demo.git
F0906 03:59:52.093018       1 builder.go:204] Error: build error: error: pathspec 'master' did not match any file(s) known to git.

**Comment by siamaksade** [comment]
Fixed in https://github.com/OpenShiftDemos/openshift-cd-demo/commit/934cbb0863a7e935517f129a3bd2cf0c84b51594
