### ISSUE TITLE
gogs credentials not working for me

### ISSUE THREAD

**Issue by jr00n** [siamaksade/openshift-cd-demo#30]
There is already a user gogs defined in Gogs, but what is the password?
The user admin with password gogs is not working.

**Comment by jr00n** [comment]
User gogs i've found ;)

user: gogs
password: password

**Comment by jr00n** [comment]
@siamaksade can you please update readme.md with the correct username/password

**Comment by siamaksade** [comment]
Done. Thanks for reporting the issue
