### ISSUE TITLE
Error with build strategy

### ISSUE THREAD

**Issue by tgaillard1** [siamaksade/openshift-cd-demo#34]
I'm getting the error below when I try to create the demo.  It appears it has to do with building the pipeline in Jenkins.  I've done the steps to enable the Pipeline tech preview feature but I'm not sure how to validate that and if that has any correlation to the build error.

Please let me know if you need more information.  

oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Error from logs:

Error from server: unrecognized build strategy: api.BuildStrategy{DockerStrategy:(*api.DockerBuildStrategy)(nil), SourceStrategy:(*api.SourceBuildStrategy)(nil), CustomStrategy:(*api.CustomBuildStrategy)(nil)}

**Comment by banchuanyu** [comment]
meet the same error.
`[vagrant@rhel-cdk openshift-cd-demo]$ oc process -f cicd-template.yaml | oc create -f -
route "jenkins" created
deploymentconfig "jenkins" created
rolebinding "default_edit" created
service "jenkins-jnlp" created
service "jenkins" created
service "nexus" created
route "nexus" created
imagestream "nexus" created
deploymentconfig "nexus" created
service "gogs" created
service "postgresql-gogs" created
route "gogs" created
imagestream "gogs" created
deploymentconfig "gogs" created
deploymentconfig "postgresql-gogs" created
pod "install-gogs" created
configmap "gogs-install" created
service "postgresql-sonarqube" created
service "sonarqube" created
route "sonarqube" created
imagestream "sonarqube" created
deploymentconfig "postgresql-sonarqube" created
deploymentconfig "sonarqube" created
Error from server: unrecognized build strategy: api.BuildStrategy{DockerStrategy:(*api.DockerBuildStrategy)(nil), SourceStrategy:(*api.SourceBuildStrategy)(nil), CustomStrategy:(*api.CustomBuildStrategy)(nil)}`

**Comment by tgaillard1** [comment]
This was due to the OpenShift version I was running.  This builds correctly now so this issue can be closed.
