### ISSUE TITLE
Nexus and SonarQube timeout while deploying

### ISSUE THREAD

**Issue by cbeldacap** [siamaksade/openshift-cd-demo#50]
Hello,
I just found this nice example and decided to follow it. At the end, Jenkins and Gogs are working just fine, but I'm having timeout problems with both Nexus and Sonar.

![image](https://user-images.githubusercontent.com/20857839/28965373-140365f6-7911-11e7-9372-f7ece1a5192f.png)

![image](https://user-images.githubusercontent.com/20857839/28965402-2c457f8c-7911-11e7-9824-53c140ca4df9.png)

Could it be something related with my PC resources?
OS: Windows10
RAM: 8GB

**Comment by sidd-harth** [comment]
Hi @cbeldacap I get same issue. For me Nexus doesnt deploy, do you have any workaround?

**Comment by cbeldacap** [comment]
@sidd-harth I'm afraid I have no more info about that, but it seemed (at least for **my** issue) something related with resources. 8GB is not enough I think.
