### ISSUE TITLE
Error while running cicd/tasks-pipeline for the 1st time

### ISSUE THREAD

**Issue by cbeldacap** [siamaksade/openshift-cd-demo#52]
Hi all,

I wanted to run the CICD/Tasks pipeline on Jenkins, but I received this error:

![pipeline-error-openshift-cd-demo](https://user-images.githubusercontent.com/20857839/29556053-e9800092-8724-11e7-9d5e-11621dbd2888.PNG)

Did anyone experience a similar problem?

Thanks a lot in advance,
Cristóbal

**Comment by cbeldacap** [comment]
I did not deploy the artifact in Nexus, does it mean something here? Is it possible that this process is retrieving the artifact from there?

![image](https://user-images.githubusercontent.com/20857839/29559533-a8f9eabe-872f-11e7-8f87-49b797a313c9.png)

**Comment by blekinge** [comment]
Run this to fix the missing image stream
```
oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json -n openshift --as=system:admin
```
