### ISSUE TITLE
could not login to jenkins UI

### ISSUE THREAD

**Issue by vnsharsha** [siamaksade/openshift-cd-demo#59]
when tried login with openshift orgin credentials system-admin 
ERROR: &quot;system&quot; is prohibited as a full name for security reasons. occurs
or says missing overall read permission. what are the credentials that I should use to login into jenkins??

**Comment by g00nix** [comment]
I got the same error today. I installed via openshift.

**Comment by cbeldacap** [comment]
@vnsharsha @gun1x The same happens for me with OpenShift Origin. Is there any update about this?

Thnx in advance

**Comment by cbeldacap** [comment]
@gun1x @vnsharsha I just made a test with `admin/admin` as they are SonarQube's credentials as well and it worked :)

It should be integrated with an LDAP or something to make it more "pro".

Should we close this then?
