### ISSUE TITLE
SonarQube pod container creation fails

### ISSUE THREAD

**Issue by deepjyotsingh** [siamaksade/openshift-cd-demo#77]
9:53:14 PM | Warning | Failed Mount | Unable to mount volumes for pod "sonarqube-2-98f7p_cicd(1f2dc0dc-2159-11e8-afb6-08002700457a)": timeout expired waiting for volumes to attach/mount for pod "cicd"/"sonarqube-2-98f7p". list of unattached/unmounted volumes=[sonarqube-data default-token-h78vc]
-- | -- | -- | --
9:50:57 PM | Warning | Failed Mount | Unable to mount volumes for pod "sonarqube-2-98f7p_cicd(1f2dc0dc-2159-11e8-afb6-08002700457a)": timeout expired waiting for volumes to attach/mount for pod "cicd"/"sonarqube-2-98f7p". list of unattached/unmounted volumes=[sonarqube-data]

**Comment by deepjyotsingh** [comment]
[ocdemo@centos7 openshift-origin-server-v3.7.1-ab0f056-linux-64bit]$ oc get pvc
NAME             STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
sonarqube-data   Pending                                                     2h
[ocdemo@centos7 openshift-origin-server-v3.7.1-ab0f056-linux-64bit]$ oc describe pvc sonarqube-data
Name:		sonarqube-data
Namespace:	cicd
StorageClass:	
Status:		Pending
Volume:		
Labels:		<none>
Annotations:	openshift.io/generated-by=OpenShiftNewApp
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  2h		2h		167	persistentvolume-controller			Normal		FailedBinding	no persistent volumes available for this claim and no storage class is set
  1h		2m		311	persistentvolume-controller			Normal		FailedBinding	no persistent volumes available for this claim and no storage class is set

**Comment by siamaksade** [comment]
Do you have any persistent volumes available in your cluster? You can check with `oc get pv`

**Comment by deepjyotsingh** [comment]
No, do I need to create it manually?

[ocdemo@centos7 openshift-origin-server-v3.7.1-ab0f056-linux-64bit]$ oc
whoami
system
[ocdemo@centos7 openshift-origin-server-v3.7.1-ab0f056-linux-64bit]$ oc get
pvc
No resources found.

**Comment by siamaksade** [comment]
Depends on how you start your cluster. [Minishift](https://github.com/minishift/minishift) for example would create automatically
