### ISSUE TITLE
Imagestream for jboss returns 404

### ISSUE THREAD

**Issue by sshaaf** [siamaksade/openshift-cd-demo#87]
The following url is returning 404. 
https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json

I change it to : https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap70-image-stream.json

And it the ci/cd process goes ahead.

**Comment by thangtd** [comment]
Hi Guys, I got the same issue., and the solution above works. Thanks @wizshah

**Comment by siamaksade** [comment]
Fixed with 302692ff65c6e852dbed1cca9c3442648c3d91cc
