### ISSUE TITLE
Crash loops in both Nexus and Sonarqube 

### ISSUE THREAD

**Issue by charlesrichard** [siamaksade/openshift-cd-demo#94]
This is on minishift with OpenShift v3.10.14

Both Nexus and Sonarqube are hitting crashloops. 

Nexus stacktrace->

  | mkdir: cannot create directory '../sonatype-work/nexus3': Permission denied
-- | --
  | mkdir: cannot create directory '../sonatype-work/nexus3': Permission denied
  | Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to Permission denied
  | Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
  | Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
  | Unable to update instance pid: Unable to create directory /nexus-data/instances
  | /nexus-data/log/karaf.log (Permission denied)
  | Unable to update instance pid: Unable to create directory /nexus-data/instances
  | Exception in thread "Thread-2" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
  | at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
  | at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
  | at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
  | at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
  | at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
  | at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
  | at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)

Sonarqube stacktrace->

mkdir: cannot create directory '../sonatype-work/nexus3': Permission denied
--
  | mkdir: cannot create directory '../sonatype-work/nexus3': Permission denied
  | Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
  | Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
  | Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to Permission denied
  | Unable to update instance pid: Unable to create directory /nexus-data/instances
  | /nexus-data/log/karaf.log (Permission denied)
  | Unable to update instance pid: Unable to create directory /nexus-data/instances
  | Exception in thread "Thread-2" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
  | at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
  | at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
  | at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
  | at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
  | at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
  | at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
  | at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)

**Comment by siamaksade** [comment]
Sounds like some corrupted data issues on the persistent storage of Nexus and Sonatype. How can I reproduce it?

I tried it now with minishift v1.22.0+7163416 and it deployed ok. I pulled all images in advance due to low bandwidth on my internet connection so that the deployment doesn't timeout. 

<img width="1386" alt="screen shot 2018-08-06 at 11 21 44" src="https://user-images.githubusercontent.com/1174934/43708536-f519536e-996a-11e8-8338-049ed144c29d.png">

**Comment by Johnny2136** [comment]
I get a similar crash but only in SonarQube, funny it worked a couple weeks ago... 

Time | Name | Kind | Severity | Reason | Message
-- | -- | -- | -- | -- | --
8:56:57 AM | nexus-1-fhrr4 | Pod | Normal | Killing | Killing container with id docker://nexus:Need to kill Pod
8:56:57 AM | nexus-1-fhrr4 | Pod | Warning | Unhealthy | Readiness probe failed: Get http://172.17.0.14:8081/: dial tcp 172.17.0.14:8081: getsockopt: connection refused14 times in the last 3 minutes
8:56:43 AM | nexus-1 | Replication Controller | Normal | Successful Delete | Deleted pod: nexus-1-fhrr4
8:56:42 AM | nexus | Deployment Config | Normal | Replication Controller Scaled | Scaled replication controller "nexus-1" from 1 to 0
8:56:40 AM | sonarqube-1 | Replication Controller | Normal | Successful Delete | Deleted pod: sonarqube-1-r2qks
8:56:39 AM | sonarqube | Deployment Config | Normal | Replication Controller Scaled | Scaled replication controller "sonarqube-1" from 1 to 0
8:55:31 AM | sonarqube-1-r2qks | Pod | Normal | Created | Created container5 times in the last 5 minutes
8:55:30 AM | sonarqube-1-r2qks | Pod | Normal | Pulled | Container image "openshiftdemos/sonarqube@sha256:9334b80c3db67b973253559b81e7075119b8e38d0f9865867209d9f22bbe232c" already present on machine4 times in the last 5 minutes
8:55:19 AM | sonarqube-1-r2qks | Pod | Warning | Back-off | Back-off restarting failed container9 times in the last 4 minutes
8:54:36 AM | sonarqube-1-r2qks | Pod | Normal | Started | Started container4 times in the last 5 minutes
8:54:16 AM | nexus-1-fhrr4 | Pod | Normal | Started | Started container
8:54:16 AM | nexus-1-fhrr4 | Pod | Normal | Created | Created container
8:54:16 AM | nexus-1-fhrr4 | Pod | Normal | Pulled | Successfully pulled image "docker.io/sonatype/nexus3@sha256:1b1a581c76bf2a43112d4eea0077a73aadf234bb34a7b56f76fd5f3c1634dcaf"
8:53:13 AM | sonarqube-1-r2qks | Pod | Normal | Pulled | Successfully pulled image "openshiftdemos/sonarqube@sha256:9334b80c3db67b973253559b81e7075119b8e38d0f9865867209d9f22bbe232c"

**Comment by Johnny2136** [comment]
Has anyone been able to get sonarqube up and running I keep getting
```
--> Scaling sonarqube-3 to 1
--
  | error: update acceptor rejected sonarqube-3: pods for rc 'cicd/sonarqube-3' took longer than 600 seconds to become available
```

**Comment by rbaumgar** [comment]
I am using
minishift v1.20.0+1bd6d5c
CDK v3.5.0-1
running OpenShift 3.10.45

OpenShift Master: v3.10.45 
Kubernetes Master: v1.10.0+b81c8f8 
OpenShift Web Console: v3.10.45 

all pods are up and running(incl CHE) except sonarqube.
Logfile:
2018.09.25 15:06:54 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2018.09.25 15:06:54 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.09.25 15:06:55 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2018.09.25 15:06:55 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.09.25 15:06:58 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.09.25 15:06:58 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.09.25 15:07:05 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
2018.09.25 15:07:05 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.09.25 15:07:05 INFO app[][o.s.a.SchedulerImpl] SonarQube is stopped

sonarqube:7.0 image details:
Name: CentOS Base Image
Author: Siamak Sadeghianfar <siamaksade@gmail.com>
Built: 7 months ago
Digest: sha256:9334b80c3db67b973253559b81e7075119b8e38d0f9865867209d9f22bbe232c
Identifier: sha256:fb637a8bad94a69ce5bb8ee0e1c10e318c416acbad06346fa514bd78ba5616a6
Labels: build-date=20170510

**Comment by siamaksade** [comment]
The "permission denied" issue seems to be a Minishift problem of not setting correct permission on the persistent volumes. 

A workaround is to deploy the demo with `--ephemeral` flag so that no persistent volumes are used. 

Another workaround is to fix the permissions in minishift:
```
minishift ssh
chmod 777 -R /var/lib/minishift/
```

**Comment by david-maumenee** [comment]
I had the same issue. I use CDK.
I do need persistent volume and the workaround solve the problem for both nexus and Sonarqube.
```
minishift ssh
chmod 777 -R /var/lib/minishift/
```
Could you add this to the doc ?

Thanks !

**Comment by siamaksade** [comment]
Added with 219cd02453205cd0c17339908283574e9e29975c
