### ISSUE TITLE
Che no longer installs

### ISSUE THREAD

**Issue by charlesrichard** [siamaksade/openshift-cd-demo#97]
The installer job is dependant on pulling this yml from Github-> https://raw.githubusercontent.com/minishift/minishift-addons/master/add-ons/che/templates/che-single-user.yml

This has been moved out of Minishift and is now in this location-> https://raw.githubusercontent.com/minishift/minishift/master/addons/che/templates/che-single-user.yml

We need to have the installer job updated.

**Comment by charlesrichard** [comment]
PR 98 submitted for 3.10. Will do one for 3.9 too.

**Comment by siamaksade** [comment]
👍
